# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Publish to Github packages

# Trigger workflow manually
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        gpg-private-key: ${{secrets.GPG_KEY}} # not needed for BC
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # not needed for BC

    - name: Build with Maven
      run: mvn -B verify --file pom.xml -Pgpg-sign
      env:
        MAVEN_GPG_KEY: ${{secrets.GPG_KEY}}
        MAVEN_GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -Pgpg-sign
      env:
        GITHUB_TOKEN: ${{ github.token }}
        MAVEN_GPG_KEY: ${{secrets.GPG_KEY}}
        MAVEN_GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
